# Generated by Django 2.2.8 on 2020-06-04 11:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 4, 11, 39, 10, 970627, tzinfo=utc), null=True)),
                ('end_time', models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 4, 11, 39, 10, 970663, tzinfo=utc), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(max_length=50)),
                ('real_name', models.CharField(max_length=50)),
                ('tz', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('activity_periods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_activity.ActivityPeriod')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
