# Generated by Django 2.2.8 on 2020-06-04 11:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 4, 11, 40, 17, 242680, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='activityperiod',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 4, 11, 40, 17, 242644, tzinfo=utc), null=True),
        ),
    ]
